external-secrets:
  installCRDs: true
  crds:
  # -- If true, create CRDs for Cluster External Secret.
  createClusterExternalSecret: true
  # -- If true, create CRDs for Cluster Secret Store.
  createClusterSecretStore: true
  # -- If true, create CRDs for Cluster Generator.
  createClusterGenerator: true
  # -- If true, create CRDs for Cluster Push Secret.
  createClusterPushSecret: true
  # -- If true, create CRDs for Push Secret.
  createPushSecret: true