apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-vault-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/k8-IaC-lab/argocd-vault.git
      revision: HEAD
      # create an app per folder with values.yaml
      files:
      - path: apps/**/values.yaml
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "default"
      source:
      # deploy helm chart with values
        helm:
          valueFiles:
          - values.yaml
          releaseName: '{{ (split "-" .path.basename)._0 }}'
        repoURL: https://github.com/k8-IaC-lab/argocd-vault.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true