apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "kv/mydemo"
type: Opaque
stringData:
  username: <username>
  password: <password>